# OpenAI API Key (замените на ваш реальный ключ)
openai_api_key = "sk-test-key-for-development-only"

# Другие секреты можно добавить здесь
# google_api_key = "your_google_api_key"
# app_store_api_key = "your_app_store_api_key"
